services:
  - type: web
    name: moviehub-backend-api
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: JWT_SECRET
        generateValue: true
